// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PMS.DataAccessLayer;

namespace PMS.DataAccessLayer.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20211227004723_InitData")]
    partial class InitData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("PMS.ApplicationDomainLayer.ProjectModel.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Project");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2021, 12, 27, 6, 17, 21, 796, DateTimeKind.Local).AddTicks(2430),
                            Detail = "This is a test project",
                            Name = "TestProject1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2021, 12, 27, 6, 17, 21, 825, DateTimeKind.Local).AddTicks(168),
                            Detail = "This is a test project",
                            Name = "TestProject2"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2021, 12, 27, 6, 17, 21, 825, DateTimeKind.Local).AddTicks(256),
                            Detail = "This is a test project",
                            Name = "TestProject3"
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2021, 12, 27, 6, 17, 21, 825, DateTimeKind.Local).AddTicks(269),
                            Detail = "This is a test project",
                            Name = "TestProject4"
                        });
                });

            modelBuilder.Entity("PMS.ApplicationDomainLayer.TaskModel.Task1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("AssignedToUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Task1");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedToUserId = 1,
                            CreatedOn = new DateTime(2021, 12, 27, 6, 17, 21, 826, DateTimeKind.Local).AddTicks(553),
                            Detail = "This is a test task",
                            ProjectId = 1,
                            Status = 2
                        },
                        new
                        {
                            Id = 2,
                            AssignedToUserId = 2,
                            CreatedOn = new DateTime(2021, 12, 27, 6, 17, 21, 826, DateTimeKind.Local).AddTicks(2018),
                            Detail = "This is a test task",
                            ProjectId = 1,
                            Status = 3
                        },
                        new
                        {
                            Id = 3,
                            AssignedToUserId = 2,
                            CreatedOn = new DateTime(2021, 12, 27, 6, 17, 21, 826, DateTimeKind.Local).AddTicks(2042),
                            Detail = "This is a test task",
                            ProjectId = 2,
                            Status = 4
                        });
                });

            modelBuilder.Entity("PMS.ApplicationDomainLayer.UserLogin", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Username");

                    b.ToTable("UserLogin");

                    b.HasData(
                        new
                        {
                            Username = "JohnDoe",
                            Password = "jd1234"
                        },
                        new
                        {
                            Username = "JohnSkeet",
                            Password = "js5678"
                        },
                        new
                        {
                            Username = "MarkSeeman",
                            Password = "ms1234"
                        },
                        new
                        {
                            Username = "BobMartin",
                            Password = "bm5678"
                        });
                });

            modelBuilder.Entity("PMS.ApplicationDomainLayer.UserModel.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "john.doe@test.com",
                            FirstName = "John",
                            LastName = "Doe",
                            Password = "jd1234"
                        },
                        new
                        {
                            Id = 2,
                            Email = "john.skeet@test.com",
                            FirstName = "John",
                            LastName = "Skeet",
                            Password = "js5678"
                        },
                        new
                        {
                            Id = 3,
                            Email = "mark.seeman@test.com",
                            FirstName = "Mark",
                            LastName = "Seeman",
                            Password = "ms1234"
                        },
                        new
                        {
                            Id = 4,
                            Email = "bob.martin@test.com",
                            FirstName = "Bob",
                            LastName = "Martin",
                            Password = "bm5678"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
